name: py38_env
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.8
  - pip
  - pip:
    - ipykernel
    - azureml-rag[faiss]>=0.1.11
    - promptflow[azure] @https://azuremlsdktestpypi.blob.core.windows.net/repo/promptflow/promptflow-0.0.109137057-py3-none-any.whl
    - promptflow-tools==0.1.0.b5
    - promptflow-vectordb==0.1.2
    - azure-ai-ml
    - azure-cli
    - azureml-core
    - azureml-mlflow==1.53.0
    - azure-ai-contentsafety
    - keyring>=4.1.1
    - keyrings.alt
    - pytest
    - flask>=2.2.3

    # Pinned dependencies
    - azureml-inference-server-http


